# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: self-hosted
  vmImage: ubuntu-latest
  demands:
    - agent.name -equals 'MLI01189'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
- task: NodeTaskRunnerInstaller@0
  inputs:
    nodeVersion: '6'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
